import type { User } from '@/types';

export const dummyProfiles: User[] = [
  {
    id: 'dummy-user-1',
    name: 'Ananya Sharma',
    age: 24,
    location: 'Mumbai',
    gender: 'Woman',
    preferences: 'Men',
    language: 'Hindi',
    region: 'West',
    community: 'Hindu',
    bio: 'Lover of art, chai, and rainy days. Looking for someone to explore new cafes with.',
    images: ['https://images.unsplash.com/photo-1509839862600-309617c3201e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxpbmRpYW4lMjB3b21hbnxlbnwwfHx8fDE3NzAyMzY0MTN8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    interests: ['Art', 'Reading', 'Coffee'],
    datingIntent: 'Serious',
    promptAnswers: [
      { prompt: 'My simple pleasures...', answer: 'A cup of masala chai on a rainy afternoon and a good book.' }
    ],
    isVerified: true,
    trustScore: 80,
    zodiac: 'Cancer',
    pets: 'Dog Person',
    smoking: 'No',
    kids: 'Not sure',
  },
  {
    id: 'dummy-user-2',
    name: 'Rohan Verma',
    age: 28,
    location: 'Delhi',
    gender: 'Man',
    preferences: 'Women',
    language: 'English',
    region: 'North',
    community: 'Sikh',
    bio: 'Tech enthusiast by day, musician by night. Seeking meaningful conversations and spontaneous road trips.',
    images: ['https://images.unsplash.com/photo-1607081692251-d689f1b9af84?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxpbmRpYW4lMjBtYW58ZW58MHx8fHwxNzcwMTE4NDc0fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    interests: ['Music', 'Technology', 'Travel'],
    datingIntent: 'Casual',
    promptAnswers: [
      { prompt: 'A life goal of mine is...', answer: 'To travel to every state in India on my motorcycle.' }
    ],
    isVerified: false,
    trustScore: 60,
    zodiac: 'Scorpio',
    pets: 'No Pets',
    smoking: 'No',
    kids: 'Want kids',
  },
  {
    id: 'dummy-user-3',
    name: 'Priya Singh',
    age: 26,
    location: 'Bangalore',
    gender: 'Woman',
    preferences: 'Everyone',
    language: 'Kannada',
    region: 'South',
    community: 'Christian',
    bio: 'Fitness freak and dog lover. My perfect weekend involves a long hike followed by a good movie.',
    images: ['https://images.unsplash.com/photo-1524255684952-d7185b509571?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx3b21hbiUyMGdsYXNzZXN8ZW58MHx8fHwxNzcwMTc2MjkzfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    interests: ['Fitness', 'Dogs', 'Movies'],
    datingIntent: 'Serious',
    promptAnswers: [
      { prompt: 'I get way too competitive about...', answer: 'Board games. Prepare to lose.' }
    ],
    isVerified: true,
    trustScore: 100,
    zodiac: 'Aries',
    pets: 'Dog Person',
    smoking: 'Socially',
    kids: "Don't want kids",
  },
  {
    id: 'dummy-user-4',
    name: 'Vikram Reddy',
    age: 30,
    location: 'Hyderabad',
    gender: 'Man',
    preferences: 'Women',
    language: 'Telugu',
    region: 'South',
    community: 'Hindu',
    bio: 'Foodie who can cook. I believe the best stories are shared over a great meal. Also, a huge cricket fan.',
    images: ['https://images.unsplash.com/photo-1618769122190-ee85526fd40b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxtYW4lMjBsYXVnaGluZ3xlbnwwfHx8fDE3NzAyMzY0MTR8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    interests: ['Cooking', 'Cricket', 'Food'],
    datingIntent: 'Marriage',
    promptAnswers: [
      { prompt: 'Two truths and a lie...', answer: 'I\'ve met Sachin Tendulkar, I can make over 20 types of biryani, I hate spicy food.' }
    ],
    isVerified: false,
    trustScore: 40,
    zodiac: 'Leo',
    pets: 'Cat Person',
    smoking: 'No',
    kids: 'Have kids',
  },
  {
    id: 'dummy-user-5',
    name: 'Meera Kumar',
    age: 27,
    location: 'Chennai',
    gender: 'Woman',
    preferences: 'Men',
    language: 'Tamil',
    region: 'South',
    community: 'Muslim',
    bio: 'Classical dancer and a bookworm. Let\'s talk about philosophy or just enjoy a quiet evening by the sea.',
    images: ['https://images.unsplash.com/photo-1708944704441-f29f280caef1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx3b21hbiUyMGJlYWNofGVufDB8fHx8MTc3MDE5MTQ4MHww&ixlib=rb-4.1.0&q=80&w=1080'],
    interests: ['Dance', 'Books', 'Beach'],
    datingIntent: 'Figuring it out',
    promptAnswers: [],
    isVerified: true,
    trustScore: 70,
    zodiac: 'Pisces',
    pets: 'All the pets',
    smoking: 'No',
    kids: 'Not sure',
  },
];
